name: Deploy 

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3

    
    - name: Install packages
      run: npm install

    - name: Set environment variables
      env: 
          API_READ_ACCESS_TOKEN: ${{ secrets.API_READ_ACCESS_TOKEN }}
          GEMINI_API: ${{ secrets.GEMINI_API }}
          MovieSiteDB_API: ${{ secrets.MovieSiteDB_API }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_USERNAME:  ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD:  ${{ secrets.MONGO_PASSWORD }}
          MOVIE_API:  ${{ secrets.MOVIE_API }}
      run: |
       echo "processed all the environment variables" 
       echo "this is the mongo username ${MONGO_USERNAME}"
       echo "this is the mongo username $MONGO_PASSWORD"
      shell: bash

    - name: Start front and backend
      run: cd Backend ; node serverJWT.js ; cd ../my-movie-list; npm start ; echo "started the application"
      shell: bash
  
  
    
