name: Development Workflow 

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy: 
    runs-on: ubuntu-latest 
    
    steps: 
    
    - uses: actions/checkout@v3
    
    - name: Install packages
      run: npm install

    - name: Use Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: 20.3
    - run: npm ci 
    - run: npm run build  --if-present
    - run: npm test 
    - run: echo "processed all the node tests"
