name: Development Workflow 

on: 
  push:
    branches:
      - serverDev
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest 

    strategy: 
      matrix:
        node-version: [20.x]
    
    steps: 
    
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: ${{matrix.node-version}}

    
    - name: npm Install
      run: |
      cd ./server
      npm ci
      cd ../client
      npm ci

    - name: test
      run: |
      cd ./server
      npm test
      cd ../client
      npm test