name: Development Workflow 

on: 
  push:
    branches:
      - serverDev
  workflow_dispatch:

jobs:
  deploy: 
    runs-on: ubuntu-latest 
    
    steps: 
    
    - uses: actions/checkout@v3
    
    - name: Install packages
      run: | 
        cd ./server
        npm install
        cd ../client 
        npm install

    - name: Use Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: 20.3
    - run: |
        cd ./client 
        npm ci 
        npm run build  --if-present
        npm test 
        echo "processed all the node tests"
